name: replicate
version: 1.0.0
description: A community-maintained Dart client package for Replicate.com, this package let you interact with Replicate.com APIs and create predictions from the available machine learning models.
repository: https://github.com/anasfik/replicate

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  path: ^1.8.3
  http: ^1.1.0
  meta: ^1.9.1
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
